name: Run Release Please

on:
    push:
        branches:
            - main

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: false

permissions:
    contents: read

jobs:
    release-please:
        permissions:
            id-token: write # for googleapis/release-please-action to create release tag
            contents: write # for googleapis/release-please-action to create release commit
            pull-requests: write # for googleapis/release-please-action to create release PR
        runs-on: ubuntu-latest

        steps:
            - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
              id: release
              with:
                  token: ${{ secrets.RELEASE_PLEASE_ACTION_TOKEN }}

        outputs:
            release_created: ${{ steps.release.outputs.release_created }}

    publish-npm:
        runs-on: ubuntu-latest
        needs: release-please
        permissions:
            id-token: write # npm provenance
            contents: read
        if: ${{ fromJSON(needs.release-please.outputs.release_created || false) }}

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
              with:
                  node-version-file: ".nvmrc"
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: npm ci

            - name: Publish package
              run: npm publish --provenance --access public
              env:
                NPM_CONFIG_PROVENANCE: true

    build-pages:
        runs-on: ubuntu-latest
        needs: release-please
        permissions:
            contents: read
            pages: write
            id-token: write
        if: ${{ fromJSON(needs.release-please.outputs.release_created || false) }}

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build -- --base /${{ github.event.repository.name }}/ --without-notes
              env:
                  NODE_OPTIONS: --max-old-space-size=4096

            - name: Setup Pages
              uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

            - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
              with:
                  path: dist

    deploy-pages:
        name: Deploy Pages
        runs-on: ubuntu-latest
        needs:
            - release-please
            - build-pages
        permissions:
            pages: write
            id-token: write
        if: ${{ fromJSON(needs.release-please.outputs.release_created || false) }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
